In [1]:
print("hello python")

hello python


In [4]:
# addition
num1=float(input("Enter first number :"))
num2=float(input("Enter secound number :"))
sum_result=num1+num2
print(f"sum:{num1} +{num2} = {sum_result}")

Enter first number : 235.2
Enter secound number : .324


sum:235.2 +0.324 = 235.524


In [8]:
#Division
num3=int(input("enter num3 :"))
num4=int(input("enter num4 :"))
if num4==0:
    print("Error : Division by zero is not allowed")
else:
    div=num3/num4
    print(f"div : {num3} / {num4} = {div}")

enter num3 : 36
enter num4 : 6


div : 36 / 6 = 6.0


In [11]:
#area of triangle
base=int(input("enter base :"))
high=int(input("Enter high :"))
area=0.5*base*high
print(f"area of trainge with base : {base} and high : {high} /n area : {area}")

enter base : 59
Enter high : 25


area of trainge with base : 59 and high : 25 /n area : 737.5


In [12]:
#swap two numbers
num1=10
num2=20
print(f"num1 : {num1} and num2 : {num2}")
temp=num1
num1=num2
num2=temp
print(f"num1 : {num1} and num2 : {num2}")


num1 : 10 and num2 : 20
num1 : 20 and num2 : 10


In [ ]:
# Random numbers

import random
print(f"random numbers : {random.randint(1,100)}")

random numbers : 49


In [23]:
#Write a Python program to convert kilometers to miles.

km=100
convert=0.621
miles=km*convert
print(miles)

62.1


In [24]:
#Write a Python program to display calendar.

import calendar
year=2023
month=2
cal=calendar.month(year,month)
print(cal)

   February 2023
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28



In [25]:
#Write a Python program to swap two variables without temp variable.
a=10
b=20
a,b=b,a
print("a=",a)
print("b=",b)

a= 20
b= 10


In [ ]:
# Write a Python program to solve quadratic equation.
# The standard form of a quadratic equation is:
# where
# a, b and c are real numbers and
# The solutions of this quadratic equation is given by:
# 𝑎𝑥 + 𝑏𝑥 + 𝑐 = 0
# 2
# 𝑎 ≠ 0
# (−𝑏 ± (𝑏 − 4𝑎𝑐 )/(2𝑎)

In [29]:
import math

a=10
b=20
c=3
dic=b-4*a*c
if dic >0:
    r1=-b +math.sqrt(b-dic)/2*a
    r2=-b -math.sqrt(b-dic)/ 2*a
    print(r1)
    print(r2)
elif dic==0:
    r3=-b/2*a
    print(r3)
else:
    r4=-b/2*a
    dic1=math.sqrt(abs(dic))/2*a
    print(f"root 1 : {r4} + {dic1}i")
    print(f"root 2 : {r4} -{dic1}i ")
    

root 1 : -100.0 + 50.0i
root 2 : -100.0 -50.0i 


In [3]:
# Write a Python Program to Check if a Number is Positive, Negative or Zero.

num=-10
if num>0:
    print("Positive")
elif num==0:
    print("Zero")
else:
    print("Negative")

Negative


In [5]:
# Write a Python Program to Check if a Number is Odd or Even.

num=4
if num%2==0:
    print("Even")
else:
    print("Odd")

Even


In [13]:
# Write a Python Program to Check Leap Year.

year=1996
if year%400==0 and year%100==0:
    print("Leap Year")
elif year%4==0 and year%100!=0:
    print("Leap year")
else:
    print("Not Leap year")
    

Leap year


In [45]:
# Write a Python Program to Check Prime Number.

num=99

if num>1:
    for i in range(2,num):
        if num%i==0:
            print("not prime")
            break
    else:
        print("prime")
else:
    print("not prime")


not prime


In [56]:
#Write a Python Program to Print all Prime Numbers in an Interval of 1-10.

s=1
e=100
prim=[]
for i in range(s,e+1):
    if i>1:
        for j in range(2,i):
            if i%j==0:
                break
        else:
            print(i)
            prim.append(i)

print("")
print(len(prim))

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97

25


In [3]:
# Write a Python Program to Find the Factorial of a Number.

num=5
count=1
for i in range(1,num+1):
    count=count*i
print(count)

120


In [5]:
# Write a Python Program to Display the multiplication Table.

num=5
count=1
for i in range(1,11):
    count=num*i
    print(f"{num} * {i} = {count}")


5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [60]:
# Write a Python Program to Check Armstrong Number
# 156 > 1^3+5^3+6^3 if both are same the is armstrong

num=9474
tem=num
tem_str=str(tem)
leng=len(tem_str)
pov=0
for i in range(num):
    div=tem%10
    pov=pov+div**leng
    tem=tem//10
if pov == num:
    print("Armstrong Number")
else:
    print("not Armstrong")




   

Armstrong Number


In [59]:
num1=10
end=1000
newlist=[]
for num in range(num1,end+1):
    tem=num
    leng=len(str(tem))
    pov=0
    while tem > 0:
        div=tem%10
        pov=pov+div**leng
        tem=tem//10
    
    if pov == num:
        newlist.append(num)
print(newlist)

[153, 370, 371, 407]


In [ ]:
# Write a Python Program to Find the Sum of Natural Numbers.

num=10
sum=0
for i in range(num+1):
    sum=i+sum
    print(sum)
    

0
1
3
6
10
15
21
28
36
45
55


In [5]:
#Least Common Multiple (LCM):

num1=int(input("enter num1 :"))
num2=int(input("enter num2 :"))
big=max(num1,num2)
while(True):
    if big%num1==0 and big%num2==0:
        break
    big +=1
print(big)

enter num1 : 24
enter num2 : 36


72


In [1]:
import math

num1=24
num2=36
lcm=math.lcm(num1,num2)
print(lcm)


72


In [10]:
# HCF / GCD

import math

num1=24
num2=36
lcm=math.gcd(num1,num2)
print(lcm)




12


In [2]:
# HCF / GCD

num1=54
num2=24
small=0
if num1>num2:
    small=num2
else:
    small=num1

for i in range(1,small+1):
    if num1%i==0 and num2%i==0:
        hcf=i
print(hcf)



6


In [ ]:
#hcf / GCD
def hcf_bn(num1,num2):
    small=min(num1,num2)
    for i in range(1,small+1):
        if num1%i==0 and num2%i==0:
            hcf=i
    return hcf

num1=54
num2=24
hcf_bn(num1,num2)

6

In [7]:
#Write a Python Program to Convert Decimal to Binary, Octal and Hexadecimal.

num=10
print(f"Binary :{bin(num)}")
print(f"Octal :{oct(num)}")
print(f"Hexadecimal :{hex(num)}")

Binary :0b1010
Octal :0o12
Hexadecimal :0xa


In [12]:
# Write a Python Program To Find ASCII value of a character
mychar='P'
print(ord(mychar))

80


In [21]:
#Write a Python Program to Make a Simple Calculator with 4 basic mathematical
#operations.

num1=10
num2=20
print("select the number \n 1. Addition \n 2.subtraction \n 3. multiplication \n 4. Division ")
num=int(input("enter num: "))

match num:
    case 1:
        print(f"addition :{num1 + num2}")
    case 2:
        print(f"Substraction :{num1 - num2}")
    case 3:
        print(f"Multiplication :{num1 * num2}")
    case 4:
        print(f"Division :{num1 / num2}")
    case _:
        print("Incalid number")
    

select the number 
 1. Addition 
 2.subtraction 
 3. multiplication 
 4. Division 
Incalid number


In [28]:
# Write a Python Program to Display Fibonacci Sequence Using Recursion

def Fib(num):
    if num<=1:
        return num
    else:
        return (Fib(num-1) + Fib(num-2))
num=int(input("enter num :"))
if num<=0:
    print("plase enter positive number ")
else:
    for i in range(num):
        print(Fib(i))


0
1
1
2
3
5
8
13
21
34


In [33]:
#Write a Python Program to calculate your Body Mass Index.

w=50
h=1.64
bmi=round(w/h**2,2)
if bmi<=18.5:
    print("under weight")
elif 18.5 > bmi <=24.9:
    print("normal")
elif 25 > bmi <=29.9:
    print("overweight")
else:
    print("obese")

overweight


In [36]:
# Write a Python Program to calculate the natural logarithm of any number.

import math
num=55
if num<=0:
    print("positive number")
else:
    res=math.log(num)
    print(res)


4.007333185232471


In [16]:
# write a Python Program for cube sum of first n natural numbers?
def first_N(num):
    cube=0
    sum=0
    for i in range(0,num+1):
        cube=i**3
        sum=sum+cube
    print(sum)
    

num=7
first_N(num)


784


In [48]:
# Write a Python Program to find sum of array.
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
Sum=sum(arr1)+sum(arr2)
print(Sum)

12


In [46]:
import numpy as np
mylist1=[1,2,3,4]
mylist2=[1,2,3,4]
Sum=sum(mylist1)
print(Sum)

10


In [49]:
#Write a Python Program to find largest element in an array

import numpy as np

arr=np.array([10,20,30,40,3,4,4,54])
Max=max(arr)
print(Max)

54


In [50]:
l=arr[0]
for i in arr:
    if i>l:
        l=i
print(l) 

54


In [64]:
# Write a Python Program for array revase

arr=[1,2,3,4]

print(arr[::-1])

[4, 3, 2, 1]


In [76]:

# Write a Python Program for array rotation
a=7
b=3
print(a/b)
print(b%a)



2.3333333333333335
3


In [81]:
mylist=[1,2,3,4,5,6,7,8,9,10]
r=3
l=len(mylist)
r=r%l
print(mylist[r:]+mylist[:r])


[4, 5, 6, 7, 8, 9, 10, 1, 2, 3]


In [84]:
def rotation(mylist,r):
    l=len(mylist)
    r=r%l
    return(mylist[r:]+mylist[:r])

List=[1,2,3,4,5,6,7]
r=3
rotation(List,r)

[4, 5, 6, 7, 1, 2, 3]

In [85]:
# Write a Python Program to Split the array and add the first part to the end

mylist=[1,2,3,4,5,6,7,8,9]
length=len(mylist)
Div=3
Div=Div%length
start=mylist[Div:]
end=mylist[:Div]
print(start+end)

[4, 5, 6, 7, 8, 9, 1, 2, 3]


In [86]:
def Split_FE(Mylist,Div):
    length=len(mylist)
    Div=Div%length
    start=mylist[Div:]
    end=mylist[:Div]
    print(start+end)

List=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
D=3
Split_FE(List,D)

[4, 5, 6, 7, 8, 9, 1, 2, 3]


In [94]:
# Write a Python Program to check if given array is Monotonic.
## A monotonic function is a function that is either always 
## increasing or always decreasing across its entire domain. 
## This means it either preserves or reverses the order of its 
## input values.

List=[1,2,1,4]
N=D=True
for i in range(1,len(List)):
    if List[i]>List[i-1]:
        D=False
    elif List[i]<List[i-1]:
        N=False
print(N or D)
        

        


False


In [95]:
def Monotonic(List):
    IN=DE=True
    for i in range(1,len(List)):
        if List[i]>List[i-1]:
            DE=False
        elif List[i]<List[i-1]:
            IN=False
    return IN or DE

List1=[1,2,3,4]
List2=[1,2,3,1,3]
List3=[5,6,7]
print(Monotonic(List1))
print(Monotonic(List2))
print(Monotonic(List3))

True
False
True


In [100]:
import numpy as np

Matrix1=np.matrix([[1,2,3]
                  ,[1,2,3]
                  ,[1,2,3]])
Matrix2=np.matrix([[1,2,3]
                  ,[1,2,3]
                  ,[1,2,3]])
print(Matrix1*Matrix2)

[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


In [106]:
# Write a Python Program to Sort Words in Alphabetic Order.

String="Hi my name is chethan kumar"
words=[word.capitalize() for word in String.split()]
newlist=sorted(words)
for i in range(0,len(newlist)):
    print(newlist[i])


Chethan
Hi
Is
Kumar
My
Name


In [ ]:
# Write a Python Program to Remove Punctuation From a String

mystring="hi!!!!!!! hello man how are do? is everything is ok (:"
Punctuation="!@#$%^&*()_+:{}<>?,./;'[]"
newstring=" "
for i in mystring:
    if i not in Punctuation:
        newstring=newstring+i
print(newstring)

 hi hello man how are do is everything is ok 


In [ ]:
name="Chiluveri ChethanKumar"
print(name[:])

: 

In [ ]:
name="Chiluveri ChethanKumar"
print(name[:])

: 