# Arrays
- In Python, array is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together. Unlike Python lists (can store elements of mixed types), arrays must have all elements of same type. Having only homogeneous elements makes it memory-efficient.

## with import array modules

In [4]:
pip install array

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement array (from versions: none)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for array


In [5]:
import array
arr=array.array("i",[1,2,3,4,5])
print(arr)
print(type(arr))

array('i', [1, 2, 3, 4, 5])
<class 'array.array'>


In [26]:

import array as arr

# integer
Int_arr=arr.array('i',[1,2,3,4,-7,0,128,-127])
print(Int_arr)
print(type(Int_arr))


# Int_arr=arr.array('i',[1,2,3,'A'])
# print(Int_arr)  # this two lines code give error by saying in int string can't used


# Floating point number
Flo_arr=arr.array('f',[1.1,2.2,3.3,0.2,0.4])  # in same way only float type is used not
print(Flo_arr)                                # other if use it give error saying different data  type is used
print(type(Flo_arr))

# String 
# Str_arr=arr.array('u',["hello","hi","who","are","you"])

'''The array module from Python's standard library does not support storing entire strings in an array directly. 
It is specifically designed for storing primitive types like individual Unicode characters (type 'u'), integers, and floats.
If you need to handle strings, you must use a list, numpy, or another data structure since the array module is not 
appropriate for this purpose.'''

Str_arr=arr.array('u',"hello")

print(Str_arr)
print(type(Str_arr))






array('i', [1, 2, 3, 4, -7, 0, 128, -127])
<class 'array.array'>
array('f', [1.100000023841858, 2.200000047683716, 3.299999952316284, 0.20000000298023224, 0.4000000059604645])
<class 'array.array'>
array('u', 'hello')
<class 'array.array'>


C:\Users\chilu\AppData\Local\Temp\ipykernel_8728\603368149.py:26: DeprecationWarning: The 'u' type code is deprecated and will be removed in Python 3.16
  Str_arr=arr.array('u',"hello")


#### Adding elements to an Array
- insert (At particular index we add element )
    - A.insert(i, x)	Index (i) + Value (x)	Inserts x at index i, shifting other elements.
- append
    - A.append(x)	Value (x)	Adds x to the end of the array.
- extend
    - A.extend(iter)	Iterable (iter)	Adds all elements from the iterable to the end of the array.

In [30]:
import array as arr
A=arr.array('i',[1,2,3])
print(A)

# insert   
A.insert(1,4) # t performs the insertion in-place, modifying the original array directly.
print(*A)

# append
A.append(5)
print(*A)

# A.append(9,3,4,5) WILL NOT WORK ROUGE TYPEERROR 

# extend
A.extend([6])
print(*A)

B=arr.array('i',[7,8,9]) # add new array elements to old array
A.extend(B)
print(*A)


array('i', [1, 2, 3])
1 4 2 3
1 4 2 3 5
1 4 2 3 5 6
1 4 2 3 5 6 7 8 9


##### Accessing Array Items
- In order to access the array items refer to the index number. Use the index operator [ ] to access an item in a array in Python. The index must be an integer

In [55]:
import array as arr
A=arr.array('i',[1,2,3,4,5])
print(*A)
print(A[0])
print(A[-1])
print(A[:])
print(*A[2:4])

B=arr.array('f',[0.1,0.2,2.1,2.2])
print(*B)
print(B[0])
print(B[0])
print(B[-1])
print(B[:])
print(*B[2:4])


1 2 3 4 5
1
5
array('i', [1, 2, 3, 4, 5])
3 4
0.10000000149011612 0.20000000298023224 2.0999999046325684 2.200000047683716
0.10000000149011612
0.10000000149011612
2.200000047683716
array('f', [0.10000000149011612, 0.20000000298023224, 2.0999999046325684, 2.200000047683716])
2.0999999046325684 2.200000047683716


#### Removing Elements from the Array
-  remove() 
    - remove() is function, it will remove element, if the element is rept two time the first occurrence element is removed 
- pop()
    - pop() is function, by default it pop only the last element and we can use Index of to pop the specif position

In [107]:
import array as arr
A=arr.array('i',[1,2,3,4,5,6,8])
print(A.index(4)) ## to see at what index what element we have
print(*A)

A.remove(1)
print(*A)

A.pop()
print(*A)
print(A.pop(2))
print(A)

# import array as arr
# A=arr.array('i',[1,2,3,4,5,6,8,9])
# A[2]=8
# print(*A)
# A[3:]=6
# print(*A)  array is not aloes to use slice in array method but
# numpy can use it 



3
1 2 3 4 5 6 8
2 3 4 5 6 8
2 3 4 5 6
4
array('i', [2, 3, 5, 6])


In [106]:
import array as arr

# Create an array
A = arr.array('i', [1, 2, 3, 4, 5, 6, 8, 9])
A[2] = 8  # Replacing element at index 2 with 8
print(*A)

# Replacing elements from index 3 with an array, not a list
A[3:] = arr.array('i', [6])  # Using an array instead of a list
print(*A)
"""Key Differences:
Broadcasting:

NumPy allows broadcasting of scalars and lists to slices, which means you can assign a scalar value to an entire slice or replace a slice with a smaller list.
Python's array module doesn't support broadcasting. You need to explicitly match the size or type of the slice.
Flexibility:

NumPy is much more flexible with slice assignments, including broadcasting and accepting lists as valid input for slice assignments.
Python's array module is more restrictive, and slice assignments require another array."""


1 2 8 4 5 6 8 9
1 2 8 6


In [108]:
# count
A=arr.array('i',[1,1,1,2,3])
b=A.count(1)
print(b)

3


## with Numpy modules

In [28]:
import numpy as np


A=np.array([1,2,3,4,5])
print(A)
print(type(A))
print(A.dtype)

B=np.array([1.1,0.2,3.4,565.343])
print(B)
print(B.dtype)

C=np.array(["hi","hello","chethan"])
print(C)
print(type(C))
print(C.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
[1.10000e+00 2.00000e-01 3.40000e+00 5.65343e+02]
float64
['hi' 'hello' 'chethan']
<class 'numpy.ndarray'>
<U7


In [38]:
"""In NumPy, you can explicitly specify the data type of an array using 
the dtype parameter during its creation. Here’s how you can create arrays 
with different data types, similar to the type code in the array module.

"""

import numpy as np

# Integer array
int_array = np.array([1, 2, 3, 4], dtype='int32')
print(int_array)  # Output: [1 2 3 4]
print(type(int_array))
print(int_array.dtype)  # Output: int32

# float array
flo_arr=np.array([1.1,0.3,4435.65454],dtype='float32')
print(flo_arr)
print(type(flo_arr))
print(flo_arr.dtype)

# String array
str_array = np.array(["hello", "world"], dtype='str')
print(str_array)  # Output: ['hello' 'world']
print(type(str_array))
print(str_array.dtype)  # Output: <U5 (Unicode string of max length 5)>


[1 2 3 4]
<class 'numpy.ndarray'>
int32
[1.1000000e+00 3.0000001e-01 4.4356543e+03]
<class 'numpy.ndarray'>
float32
['hello' 'world']
<class 'numpy.ndarray'>
<U5


#### Adding elements to an Array


- Insert	
    - np.insert(arr, i, x)	
    - arr (array), i (index), x (value or values)	
    - Inserts x at index i, shifting other elements.
- Append	
    - np.append(arr, x)	
    - arr (array), x (value or values)	
    - Adds x to the end of the array.
- Extend 
    - (Do not use np.extend, as it is not a valid NumPy function.)
    - np.append(arr, iter)	
    - arr (array), iter (iterable)	
    - Adds all elements from the iterable iter to the array.


In [31]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

#insert 
arr=np.insert(arr,1,4) ## It creates a new array with the specified value (4) inserted at the specified index (1).
print(arr)

# append
arr=np.append(arr,5) # numpy.append creates a new array because NumPy arrays are fixed in size. Appending requires creating a new array with the additional element(s).
print(arr)

# append multiple elements
arr=np.append(arr,[7,8,9])
print(arr)
arr1=np.array([10,11,12])
arr=np.append(arr,arr1)
print(arr)

# extend Do not use np.extend, as it is not a valid NumPy function.
# arr=np.extend(arr,[6])
# print(arr)


[1 2 3]
[1 4 2 3]
[1 4 2 3 5]
[1 4 2 3 5 7 8 9]
[ 1  4  2  3  5  7  8  9 10 11 12]


##### Accessing Array Items
- In order to access the array items refer to the index number. Use the index operator [ ] to access an item in a array in Python. The index must be an integer

In [54]:
import numpy as np
A=np.array([1,2,3,4,5])
print(A)
print(A[0])
print(A[-1])
print(A[:])
print(A[2:5])


B=np.array([0.1,0.2,1.2,2.2])
print(*B)
print(B[0])
print(B[0])
print(B[-1])
print(B[:])
print(*B[2:4])


[1 2 3 4 5]
1
5
[1 2 3 4 5]
[3 4 5]
0.1 0.2 1.2 2.2
0.1
0.1
2.2
[0.1 0.2 1.2 2.2]
1.2 2.2


#### Removing Elements from the Array
-  remove() 
    - in numpy we don't have remove method
    - instead we use delete to remove element by index
- pop()
    - in numpy we don't have pop method
    - instead we use delete to remove element by index

In [91]:
import numpy as np
A=np.array([1,2,3,4,5])
print(*A)
# print(A.index(1)) # we do not have index method



A=np.delete(A,1) # by index , it delete the index element and store in the new array
print(*A)
print(A[:-1])

Delete=A[2]
A=np.delete(A,2) # by index , it delete the index element and store in the new array
print(A)
print(Delete)
print(A)
print(A[::-1])

A=np.array([1,2,3,4,5])
print(*A)
A[2]=9
print(A)
A[3:]=4
print(A)

1 2 3 4 5
1 3 4 5
[1 3 4]
[1 3 5]
4
[1 3 5]
[5 3 1]
1 2 3 4 5
[1 2 9 4 5]
[1 2 9 4 4]


In [124]:
# # count
# # A=np.array('i',[1,1,1,2,3])
# b=A.count(1)
# print(b)   no count in numpy 
# but we can use count_nonzero in numpy

A=np.array([1,1,1,2,3])
b=np.count_nonzero(A==1)
print(b)

A=np.array([1,1,1,2,2,3])
b=np.count_nonzero(A==2)
print(b)

3
2
