# Numpy

- NumPy, short for "numerical Python", is a free, open-source library for the Python programming language that provides support for large, multi-dimensional arrays: 

- What it does
    - NumPy is a scientific computing library that provides a collection of mathematical functions for working with arrays. These functions include: 
        - Linear algebra 
        - Random simulation 
        - Fourier transforms 
        - Trigonometric operations 
        - Statistical operations 
- How it works
    - NumPy is built around the concept of arrays, which are collections of elements. The array object in NumPy is called ndarray. You can create a NumPy ndarray object by using the array() function. 
- Why it's useful
    - NumPy is useful for performing optimized mathematical operations on large arrays. It's also useful for: 
        - Data importation and transformation 
        - Time series and risk analysis 
        - Trading and backtesting 
        - Excel integration 
        - Data visualization 
- How to use it
    - You can add NumPy to an existing Python installation and write Python code that makes calls and exchanges data with NumPy features and functions.

## what is array 
- An array is a data structure that stores values of same data type. In python , this is the main different between arrays and list. while python lists can contain values corresponding to different data types, arrays are in python can only contain values corresponding same data type

In [1]:
# Installation of NumPy
pip install numpy

SyntaxError: invalid syntax (2947115696.py, line 2)

In [2]:
# Import NumPy
import numpy as np
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
my_tuple=(1,2,3,4,5)
arr=np.array(my_tuple)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr # 1D - array

array([1, 2, 3, 4, 5])

In [5]:
arr.shape # 1D - array

(5,)

## 2 D - Array

In [6]:
# we can change 1D array to 2D array
# we reshape() function

l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l3=[11,12,13,14,15]
arr=np.array([l1,l2,l3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [7]:
arr.shape


(3, 5)

In [8]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [9]:
print(arr.ndim)

2


In [10]:
arr.shape

(3, 5)

In [11]:
# we reshape() function , when your are reshaping the total count of the element should be same first and last

arr1=arr.reshape(5,3)
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [12]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
arr1.shape

(5, 3)

In [14]:
arr2=arr.reshape(1,15)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [15]:
arr3=arr.reshape(15)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
print(arr3.ndim)
print(arr2.ndim)
print(arr1.ndim)
print(arr.ndim)

1
2
2
2


### indexing

In [17]:
arr=np.array([1,2,3,4,5,6,7,8,9]) # 1D array
print(arr.ndim)
print(arr.shape)
print(arr[0])
print(arr[3])
print(arr[-1])
print(arr[:])
print(arr[2:6])
print(arr[-4:-3])


1
(9,)
1
4
9
[1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[6]


In [18]:

import numpy as np
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
2


In [19]:
# in left side of ( , ) which row index we want 
# arr2[,]
print("\nAll rows and columns:")
print(arr2[:,])
print()
print(arr2[:,:])
# print(arr2[,:])  # will get error
print("----------------- row")
print(arr2[0])

print(arr2[1])

print(arr2[2])

print("----------------- column")
print(arr2[:,0])

print(arr2[:,1])

print(arr2[:,2])


print(arr2[:,3])

print(arr2[:,4])

print("---------------------- one elements ")
print(arr2[0,0]) # (0,0) element
print(arr2[0,1]) 
print(arr2[0,4])
print(arr2[2,3])


print("-------------------------")
print(arr2[0:3])
print("-------------------------")
print(arr2[0:2])
print("-------------------------")
print(arr2[0:1])






All rows and columns:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
----------------- row
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
----------------- column
[ 1  6 11]
[ 2  7 12]
[ 3  8 13]
[ 4  9 14]
[ 5 10 15]
---------------------- one elements 
1
2
5
14
-------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-------------------------
[[1 2 3 4 5]]


In [20]:

print(arr2[0:3,])
print("-------------------------")
print(arr2[0:2,])
print("-------------------------")
print(arr2[0:1,])
print("-------------------------")



print(arr2[:,:])
print("-------------------------")
print(arr2[:,:5])
print("-------------------------")
print(arr2[:,:4])
print("-------------------------")

print(arr2[:,:3])
print("-------------------------")
print(arr2[:,:2])
print("-------------------------")
print(arr2[:,:1])
print("-----------------")


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-------------------------
[[1 2 3 4 5]]
-------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-------------------------
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]
-------------------------
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
-------------------------
[[ 1  2]
 [ 6  7]
 [11 12]]
-------------------------
[[ 1]
 [ 6]
 [11]]
-----------------


In [21]:
print(arr2)
print("-----------------")
print(arr2[0:0,0:0])
print("-----------------")
print(arr2[0:1,0:1])
print("-----------------")
print(arr2[0:2,0:2])
print("-----------------")
print(arr2[0:3,0:3])
print("-----------------")
print(arr2[0:4,0:4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-----------------
[]
-----------------
[[1]]
-----------------
[[1 2]
 [6 7]]
-----------------
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
-----------------
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


In [22]:
print(arr2[0:1,0:5])
print("-----------------")
print(arr2[0:2,0:5])
print("-----------------")
print(arr2[0:3,0:5])
print("-----------------")

[[1 2 3 4 5]]
-----------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-----------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-----------------


In [23]:
print(arr2[:,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [24]:
arr2[0:3,0:1]

array([[ 1],
       [ 6],
       [11]])

In [25]:
arr2[0:3,1:2]
print("-----------------")
print(arr2[1:4,1:4])

-----------------
[[ 7  8  9]
 [12 13 14]]


In [26]:
arr2[1:3,3:5]

array([[ 9, 10],
       [14, 15]])

In [27]:
arr2[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [28]:
arr2[0:3,3:5]

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

In [29]:
arr2[2:3,4:5]

array([[15]])

In [30]:
arr2[1:2,4:5]

array([[10]])

In [31]:
arr2[0:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
arr2[1:3,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
arr2[0:3,0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [34]:
arr2[0:3,2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

In [35]:
arr2[0:3,0:5]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
arr2[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [37]:
arr2[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [38]:
arr2[0:2,3:5]

array([[ 4,  5],
       [ 9, 10]])

In [39]:
arr2[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [40]:
print(arr2[0:1,0:1],arr2[2:3,4:5])

[[1]] [[15]]


In [41]:
arr2[2:3,4:5]

array([[15]])

In [42]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [43]:
arr2.shape

(3, 5)

In [44]:
arr2[1:2,1:4]

array([[7, 8, 9]])

In [45]:
arr1=np.arange(0,10)
print(arr1)
print(arr1.reshape(2,5))

arr2=np.arange(0,10).reshape(2,5)
print(arr2)
# print(arr1*arr2) # operands could not be broadcast together with shapes (10,) (2,5)
print(arr1.reshape(2,5)*arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  4  9 16]
 [25 36 49 64 81]]


In [46]:
# to find Dimension (ndim)
arr=np.array([1,2,3])
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)


1
2
3


In [47]:
arr=np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [48]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [49]:
ARR1=np.linspace(1,50,50)
ARR1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [50]:
type(ARR1)

numpy.ndarray

In [51]:
ARR1.shape

(50,)

In [52]:
Arr=np.array([1,2,3,4,5,6,6,3,4,523,23])
Arr

array([  1,   2,   3,   4,   5,   6,   6,   3,   4, 523,  23])

In [53]:
Arr[3:]=100

In [54]:
Arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100, 100])

### 3 D array


In [55]:
Arr=np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
])
print(Arr)

print("\n",Arr.shape)
print(type(Arr))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

 (3, 3, 3)
<class 'numpy.ndarray'>


In [56]:
print(Arr)
print("--------------------------------")
print(Arr[:,:,:])
print("-----------------------------")
print(Arr[0:,:,])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
--------------------------------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
-----------------------------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [57]:
print(Arr[0:,:,:])
print("------------------------ 1 ---")
print(Arr[1:,:,:])
print("------------------------ 2 ---")
print(Arr[2:,:,:])
print("------------------------  3 ---")
print(Arr[3:,:,:])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
------------------------ 1 ---
[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
------------------------ 2 ---
[[[19 20 21]
  [22 23 24]
  [25 26 27]]]
------------------------  3 ---
[]


In [58]:
print(Arr[0])         # first 2d array (layer 0)
print("\n",Arr[1])    # second 2d array (layer 1)
print("\n",Arr[2])    # third 2d array (layer 2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[10 11 12]
 [13 14 15]
 [16 17 18]]

 [[19 20 21]
 [22 23 24]
 [25 26 27]]


In [59]:
print(Arr[0,:,:])   # Entire layer 0(same as Arr[0])
print("---------------------------")
print("\n",Arr[:,1:,:])  # Row 1 from all layers
print("-----------------------------")
print(Arr[:,:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------------------

 [[[ 4  5  6]
  [ 7  8  9]]

 [[13 14 15]
  [16 17 18]]

 [[22 23 24]
  [25 26 27]]]
-----------------------------
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [60]:
print(Arr[:,0:,:]) 
print("----------------------------")
print(Arr[:,1:,:])                  # Row 1 from all layers.
print("----------------------------")
print(Arr[:,2:,:])
print("----------------------------")
print(Arr[:,3:,:])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
----------------------------
[[[ 4  5  6]
  [ 7  8  9]]

 [[13 14 15]
  [16 17 18]]

 [[22 23 24]
  [25 26 27]]]
----------------------------
[[[ 7  8  9]]

 [[16 17 18]]

 [[25 26 27]]]
----------------------------
[]


In [61]:
print(Arr)
print("__________________")
print(Arr[:,:,0])
print("__________________")
print(Arr[:,:,1])
print("__________________")
print(Arr[:,:,2])           # Column 2 from all layers.


print("__________________")
print(Arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
__________________
[[ 1  4  7]
 [10 13 16]
 [19 22 25]]
__________________
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]
__________________
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
__________________
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [62]:
# Accessing Specific Elements
# You can use three indices: [layer, row, column].

# arr3[0, 1, 2] → Element at layer 0, row 1, column 2 (6).
# arr3[2, 0, 1] → Element at layer 2, row 0, column 1 (20).
print(Arr[0,0,0]) #  Accessing Specific Elements 1 
print(Arr[0,0,1]) # 2
print(Arr[0,0,2]) # 3
print(Arr[0,1,0]) # 4

print(Arr[1,0,0]) # 10
print(Arr[1,1,1]) # 14
print(Arr[1,1,2]) # 15
print(Arr[1,2,2]) # 18

print(Arr[2,0,0]) # 19
print(Arr[2,1,1]) # 23
print(Arr[2,2,2]) # 22




1
2
3
4
10
14
15
18
19
23
27


In [63]:
Arr[0:,0:,0:]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [64]:
Arr[:1,:,:]  # : -> left = row  , :  ->  right = column  <-- [:] 
             # and at right side the is 1 then we should give it as 2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [65]:
Arr[:2,:,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [66]:
Arr[:3,:,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [67]:
Arr[:,:3,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [68]:
Arr[:,:2,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [69]:
Arr[:,:1,:]

array([[[ 1,  2,  3]],

       [[10, 11, 12]],

       [[19, 20, 21]]])

In [70]:
Arr[:,1:,:]

array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[22, 23, 24],
        [25, 26, 27]]])

In [71]:
Arr[:,2:,:]

array([[[ 7,  8,  9]],

       [[16, 17, 18]],

       [[25, 26, 27]]])

In [72]:
print(Arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [73]:
Arr[:,0:1,:]

array([[[ 1,  2,  3]],

       [[10, 11, 12]],

       [[19, 20, 21]]])

In [74]:
Arr[:,0:2,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [75]:
Arr[:,1:2,:]

array([[[ 4,  5,  6]],

       [[13, 14, 15]],

       [[22, 23, 24]]])

In [76]:
Arr[1:2,1:3,0:1]

array([[[13],
        [16]]])

In [77]:
Arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [78]:
Arr[2:,1:2,:]

array([[[22, 23, 24]]])

In [79]:
Arr[2:,:,:]

array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [80]:
Arr[2:,:,0:2]

array([[[19, 20],
        [22, 23],
        [25, 26]]])

In [81]:
Arr[1:2,:,0:1]

array([[[10],
        [13],
        [16]]])

In [82]:
Arr[:1,:1,:]

array([[[1, 2, 3]]])

In [83]:
Arr[:1,:1,:1]

array([[[1]]])

In [84]:
Arr[:3,:,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [85]:
# higher Dimensional arrays (ndmin)
import numpy as np
arr=np.array([1,2,3,4,5], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [86]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1:,0:1])
print(arr[1,0])

[[5]]
5


In [87]:
# to check data type of array
print(arr.dtype)
a=np.array(['hi','hello'])
print(a.dtype)

int64
<U5


In [88]:
# Check number of Dimensions
import numpy as np
A1=np.array([1,2,3,4,5])
A2=np.array([[1,2,3],[4,5,6]])
A3=np.array([
    [[1,2,3],[4,5,6]]
    ,[[7,8,9],[10,11,12]]
    ,[[13,14,15],[16,17,18]]
             ])
A4=np.array([1,2,3,4,5,6,7,8,9,10],ndmin=4)
A5=np.array([1,2,3,4,5,6,7,8,9,10],ndmin=5)
print(A1)
print(A2)
print(A3)
# type
print(A1.dtype)
print(type(A1))
# Dimension 
print(A1.ndim)
print(A2.ndim)
print(A3.ndim)
print(A4.ndim)
print(A5.ndim)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
int64
<class 'numpy.ndarray'>
1
2
3
4
5


In [89]:
# step
print(A1[0:5:2])
print(A1[1:5:2])

[1 3 5]
[2 4]


In [90]:
#change the data type of array
B=np.array([1.1,2.1,3.1])
B1=B.astype('i')
print(B1)
print(B)
print(B.dtype)
print(B1.dtype)
B1=np.append(B1,4)
print(B)
print(B1)

[1 2 3]
[1.1 2.1 3.1]
float64
int32
[1.1 2.1 3.1]
[1 2 3 4]


In [91]:
# Copy 
# changes in original array
C=np.array([1,2,3,4,5])
C1=C.copy()
C[0]=23
print(C1)
print(C)

print("----------")
# changes in copy in array
C1[0]=44
print(C1)
print(C)


[1 2 3 4 5]
[23  2  3  4  5]
----------
[44  2  3  4  5]
[23  2  3  4  5]


In [92]:
# view 
# changes in original array
D=np.array([1,2,3,4,5])
D1=D.view()
D[0]=11
print(D)
print(D1)

# changes in view array 
D1[2]=22
print(D)
print(D1)

[11  2  3  4  5]
[11  2  3  4  5]
[11  2 22  4  5]
[11  2 22  4  5]


In [93]:
# array iteration  
# 1D
for i in D:
    print(i)
print("Dim :",D.ndim)
# 2D

D2=np.array([[1,2,3],[4,5,6]])
for i in D2:
    for j in i:
        print(j)
print("Dim :",D2.ndim)

# 3D
D3=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]    
    ])
for i in D3:
    for j in i:
        for k in j:
            print(k)
print("Dim :",D3.ndim)

11
2
22
4
5
Dim : 1
1
2
3
4
5
6
Dim : 2
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
Dim : 3


In [ ]:
# array nditer (automatic fix the loop and print the element of array 1D, 2D, 3D, 4D)
import numpy as np
Arr=np.array([
    [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
    ],
    [[[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
    ]
    ])
print(Arr)
print(Arr.ndim)


[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]
   [25 26 27]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]
   [25 26 27]]]]
4


In [100]:
for i in np.nditer(Arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [3]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)  # Converts to bytes ('b1', 'b2', 'b3')


np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [2]:
arr = np.array([[1, 2], [3, 4]])

with np.nditer(arr, flags=['c_index']) as it:
    for x in it:
        print(f"Value: {x}, C Index: {it.index}")


Value: 1, C Index: 0
Value: 2, C Index: 1
Value: 3, C Index: 2
Value: 4, C Index: 3


In [5]:
import numpy as np
arr=np.array([1,2,3])
for i in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(i)



np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [6]:
import numpy as np
a=np.array([1,2,3])
for i in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [12]:
a=np.array([[1,2,3],[4,5,6]])
with np.nditer(a,flags=['c_index']) as it:
    for i in it:
        print(f"value :{i} , C index : {it.index}")


value :1 , C index : 0
value :2 , C index : 1
value :3 , C index : 2
value :4 , C index : 3
value :5 , C index : 4
value :6 , C index : 5


In [14]:
import numpy as np
A=np.array([1,2,3,4,5])
for i in np.nditer(A,flags=['buffered'],op_dtypes=['S']):
    print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')


In [16]:
A1=np.array([[1,2,3],[4,5,6]])
with np.nditer(A1,flags=['c_index']) as it:
    for i in it:
        print(f"valuse :{i}, C index :{it.index}")


valuse :1, C index :0
valuse :2, C index :1
valuse :3, C index :2
valuse :4, C index :3
valuse :5, C index :4
valuse :6, C index :5


In [20]:
it=np.nditer(A1,flags=['c_index'])
try:
    for i in it:
        print(f"values :{i}, C index :{it.index}")
finally:
    del it

values :1, C index :0
values :2, C index :1
values :3, C index :2
values :4, C index :3
values :5, C index :4
values :6, C index :5


### Numpy Joining array
 - for joining we usr : concatenate()

In [5]:
import numpy as np

# 1D array

Ar=np.array([1,2,3])
Ar1=np.array([4,5,6])
A1=np.concat((Ar,Ar1))
A2=np.concatenate((Ar,Ar1))
print(A1)
print(A2)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [16]:
# 2D array

B=np.array([[1,2,3],[4,5,6]])
B1=np.array([[7,8,9],[10,11,12]])
Br1=np.concat((B,B1))
Br2=np.concatenate((B,B1))
print(Br1)
print(Br2)

#

Br3=np.concat((B,B1),axis=1)
print(Br3)

Br4=np.concatenate((B,B1),axis=1)
print(Br4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Numpy Joining array 
 - for joining we use : stack()
 -  stack and concatenate both are same but one difference is stack is along a new line
 - stack will axis, if not use axis it will take as 0
 - stack change 1D array to 2D array .......

In [26]:
R=np.array([1,2,3])
R1=np.array([4,5,6])
R2=np.stack((R,R1))  # axis =0
print(R2)
R3=np.stack((R,R1),axis=1)
print(R3)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [27]:
# stack is haveing both row(use = hstack()) and columns(use= dstack()) and depth (use= dstack())

R4=np.hstack((R,R1))
print(R4)
R5=np.dstack((R,R1))
print(R5)

[1 2 3 4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
R6=np.dstack((R,R1))
print(R6)



[[[1 4]
  [2 5]
  [3 6]]]


In [17]:
R=np.array([[1,2,3],[4,5,6]])
R1=np.array([[7,8,9],[10,11,12]])
R2=np.stack((R,R1))  # axis =0
print(R2)
R3=np.stack((R,R1),axis=1)
print(R3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [ ]:
# stack is haveing both row(use = hstack()) and columns(use= dstack()) and depth (use= dstack())

R4=np.hstack((R,R1))
print(R4)
R5=np.dstack((R,R1))
print(R5)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [ ]:
R=np.array([[1,2,3],[4,5,6]])
R1=np.array([[7,8,9],[10,11,12]])
R2=np.stack((R,R1))  # axis =0
print(R2)
R3=np.stack((R,R1),axis=1)
print(R3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [30]:
R6=np.dstack((R,R1))
print(R6)



[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


#### Array splitting
- array_split()

In [ ]:
import numpy as np

# 1D 
A=np.array([1,2,3,4,5,6])
na=np.array_split(A,3)
print(na)
na=np.array_split(A,4)
print(na)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [34]:
# access the element
print(na[0])
print(na[1])
print(na[2])

[1 2]
[3 4]
[5]


In [42]:
# 2D
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
na=np.array_split(A,3)
print(na)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]


#### Searching array
- np.where() is used

In [18]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

(array([3, 5, 6]),)


In [21]:
a1=np.array([1,2,3,4,5])
x=np.searchsorted(a1,3)
print(x)

2


In [19]:
a1=np.array([9,8,7,6,5,4,3,2,1])
x=np.searchsorted(a1,3)
print(x)

0


In [ ]:
a1=np.array([9,8,7,6,5,4,3,2,1])
x=np.searchsorted(a1,7) # if it is unsorted the result is not current 
print(x)
a1=np.sort(a1)
print(a1)
x=np.searchsorted(a1,7)
print(x)


9
[1 2 3 4 5 6 7 8 9]
6


In [23]:
a2=np.array([1,2,3,4,4,5,5])
x=np.searchsorted(a2,4)
print(x)
x=np.searchsorted(a2,5)
print(x)

3
5


In [29]:
# search form right side
ar=np.array([6,7,8,9])
x=np.searchsorted(ar,7,side='right')
print(x)

2
